version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: agro-conecta-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: agro_conecta
      POSTGRES_USER: agro_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Allow external connections
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"  # Expose PostgreSQL port externally for n8n connection
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Custom PostgreSQL configuration for external access
      - ./backend/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./backend/config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: >
      postgres 
      -c listen_addresses='*'
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
    networks:
      - agro-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agro-conecta-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      FRONTEND_URL: https://agroconecta.conext.click
      DATABASE_URL: postgresql://agro_user:${POSTGRES_PASSWORD}@postgres:5432/agro_conecta
      JWT_SECRET: ${JWT_SECRET}
      ASAAS_API_KEY: ${ASAAS_API_KEY}
      ASAAS_ENVIRONMENT: production
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      # CORS configuration for production
      CORS_ORIGINS: https://agroconecta.conext.click,https://www.agroconecta.conext.click
    ports:
      - "5000:5000"  # Expose backend port for external access (temporary for debugging)
    expose:
      - "5000"
    depends_on:
      - postgres
    networks:
      - agro-network


  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agro-conecta-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: https://api.agroconecta.conext.click
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - agro-network


volumes:
  postgres_data:

networks:
  agro-network:
    driver: bridge
