version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: agro-conecta-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: agro_conecta
      POSTGRES_USER: agro_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agro-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agro-conecta-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      FRONTEND_URL: https://agroconecta.conext.click
      DATABASE_URL: postgresql://agro_user:${POSTGRES_PASSWORD}@postgres:5432/agro_conecta
      JWT_SECRET: ${JWT_SECRET}
      ASAAS_API_KEY: ${ASAAS_API_KEY}
      ASAAS_ENVIRONMENT: production
    expose:
      - "5000"
    depends_on:
      - postgres
    networks:
      - agro-network


  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agro-conecta-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: https://api.agroconecta.conext.click
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - agro-network


volumes:
  postgres_data:

networks:
  agro-network:
    driver: bridge
