services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: agro-conecta-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: agro_conecta
      POSTGRES_USER: agro_user
      POSTGRES_PASSWORD: agro_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agro-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agro-conecta-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      FRONTEND_URL: http://localhost:3002
      DATABASE_URL: postgresql://agro_user:agro_password@postgres:5432/agro_conecta
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: http://localhost:5000/auth/google/callback
      ASAAS_API_KEY: ${ASAAS_API_KEY}
      ASAAS_ENVIRONMENT: sandbox
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - agro-network
    command: npm start

volumes:
  postgres_data:

networks:
  agro-network:
    driver: bridge
